platform:ios,'9.0'
pod ‘AFNetworking’
pod 'SDWebImage', '~> 3.7.1'
pod 'SDAutoLayout'
pod 'SVProgressHUD'
pod 'AlipayX'
pod 'YAScrollSegmentControl'
pod 'FMDB'
pod 'TTTAttributedLabel'
pod 'CDRTranslucentSideBar'
pod 'FastAnimationWithPOP'
pod 'AMapSearch'
pod 'AMap2DMap'
pod 'AMapLocation'
pod 'UMengMessage'
pod 'UMengFeedback'
pod 'UMengSocial'
pod 'UMengAnalytics'
pod 'JSBadgeView'
pod 'RealReachability'